### PR TITLE
1 layout

### PR DESCRIPTION
**Pull request by huyeefntrang06060410**

### CODE REVIEW

**Review by dangthanhduy2003 — APPROVED** [review]

**Review by dangthanhduy2003 — APPROVED** [review]
jgjkgkjg

**Review by dangthanhduy2003 — APPROVED** [review]
hvhjvv

**Review by dangthanhduy2003 — APPROVED** [review]
jgbjh

**Review by dangthanhduy2003 — APPROVED** [review]
kjkjhg

**Comment by huyeefntrang06060410** [comment]
> kjkjhg

jjbhkjbkj

**Review by huyeefntrang06060410 — COMMENTED** [review]
dtgthe

**Review by dangthanhduy2003 — APPROVED** [review]

**Review by dangthanhduy2003 — APPROVED** [review]

**Pull request closed without merging**
